# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "http", "~>2.0.3"

gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.3.0", :group => [:development, :test]
gem "rspec", "~>3.5.0", :group => [:development, :test]
gem "vcr", "~>3.0.3", :group => [:development, :test]
gem "webmock", "~>2.1.0", :group => [:development, :test]
gem "hoe", "~>3.15", :group => [:development, :test]

# vim: syntax=ruby
