---
http_interactions:
- request:
    method: get
    uri: https://sdk-test.stratumn.rocks/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Connection:
      - close
      Host:
      - sdk-test.stratumn.rocks
      User-Agent:
      - http.rb/2.0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '174'
      Connection:
      - close
      Access-Control-Allow-Origin:
      - "*"
      Date:
      - Thu, 11 Aug 2016 15:21:50 GMT
      Server:
      - nginx
      X-Cache:
      - Miss from cloudfront
      Via:
      - 1.1 7c685272394b8e1c5674f9160261a2bd.cloudfront.net (CloudFront)
      X-Amz-Cf-Id:
      - dvZB7G67kaCKUXDjExTgvibRGEjx5wpbIWZFM-3PbZmEUxk3LtO7TQ==
    body:
      encoding: UTF-8
      string: '{"id":"572778542311def814311315","name":"sdk-test","agentInfo":{"functions":{"init":{"args":["title"]},"addMessage":{"args":["content","author"]},"addTag":{"args":["tag"]}}}}'
    http_version: 
  recorded_at: Thu, 11 Aug 2016 15:21:50 GMT
recorded_with: VCR 3.0.3
